name: Test translations and maintenance tools

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle exec rspec
      - run: bundle exec ruby script/locale_check.rb
      - run: bundle exec ruby script/pluralization.rb --check
